library(brainflow)

params <- get_brainflow_input_params()
board_shim <- get_board_shim_object(BoardIds()$SYNTHETIC_BOARD["Id"], params)
board_shim$prepare_session()
board_shim$start_stream()
Sys.sleep(time = 5)
board_shim$stop_stream()
data <- board_shim$get_current_board_data(as.integer(250))
board_shim$release_session()
