library(reticulate)
use_python("/home/osboxes/venv_brainflow/bin/python")
library(brainflow)

board_shim <- get_board_shim(Boards()$Cython["Type"], "/dev/emulated_cython")
prepare_session(board_shim)
start_stream(board_shim, 3600)
Sys.sleep(time = 5)
stop_stream(board_shim)
data <- get_current_board_data(board_shim, 250)

data_handler <- get_data_handler(Boards()$Cython["Type"], data)
preprocess_data(data_handler, 1, 50, TRUE)
preprocessed_data <- get_data(data_handler)
head(preprocessed_data)
release_session(board_shim)
