[package]
name = "brainflow-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
generate_binding = ["bindgen"]

[build-dependencies]
bindgen = { version = "0.59.1", optional = true }
cmake = "0.1"
