[package]
name = "brainflow-sys"
version = "0.1.0"
edition = "2018"
description = "FFI bindings to brainflow"
readme = "README.md"

[features]
generate_binding = ["bindgen"]

[build-dependencies]
bindgen = { version = "0.59.1", optional = true }
cmake = "0.1"
