[brainflow]
git-tree-sha1 = "8452b101f71dca8b177aa104b2d2cb2576c8cdc8"
lazy = true

    [[brainflow.download]]
    sha256 = "cbdbf523553ae4ff5754a285a13da1c1a956699c14e2e3dde60ac5c4d0cc0a1f"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.6.1/compiled_libs.tar"
