[brainflow]
git-tree-sha1 = "6ef842cfbeb8127313d87330ba2cca8fae498db2"
lazy = true

    [[brainflow.download]]
    sha256 = "1be5ca3d1cfa7352a3ab55a7407c714d64777fba246732342029fd5d8124a4c8"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/4.9.3/compiled_libs.tar"
