#include <array>
#include <chrono>
#include <ctype.h>
#include <map>
#include <set>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <thread>

#include "brainflow_constants.h"
#include "cmd_def.h"
#include "helpers.h"
#include "muse_constants.h"
#include "muse_functions.h"
#include "muse_types.h"
#include "uart.h"

#include <iostream>

// read Bluetooth_Smart_Software_v1.3.1_API_Reference.pdf to understand this code

namespace MuseBLEDLib
{
    volatile int exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
    char uart_port[1024];
    int timeout = 15;
    volatile bd_addr connect_addr;
    volatile uint8 connection = -1;
    volatile uint16 muse_handle_start = 0;
    volatile uint16 muse_handle_end = 0;
    volatile State state =
        State::NONE; // same callbacks are triggered by different methods we need to differ them
    volatile bool should_stop_stream = true;
    bool initialized = false;
    std::thread read_characteristic_thread;
    std::set<uint16> ccids;
    std::map<std::string, uint16> characteristics;

    void read_characteristic_worker ()
    {
        while (!should_stop_stream)
        {
            read_message (UART_TIMEOUT);
        }
    }

    int initialize (void *param)
    {
        if (!initialized)
        {
            if (param == NULL)
            {
                return (int)BrainFlowExitCodes::UNABLE_TO_OPEN_PORT_ERROR;
            }
            struct MuseInputData *input = (struct MuseInputData *)param;
            strcpy (uart_port, input->uart_port);
            timeout = input->timeout;
            bglib_output = output;
            exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
            initialized = true;
        }
        return (int)BrainFlowExitCodes::STATUS_OK;
    }

    int open_device (void *param)
    {
        if (uart_open (uart_port))
        {
            return (int)BrainFlowExitCodes::UNABLE_TO_OPEN_PORT_ERROR;
        }
        int res = reset_ble_dev ();
        if (res != (int)BrainFlowExitCodes::STATUS_OK)
        {
            return res;
        }
        exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
        state = State::OPEN_CALLED;
        ble_cmd_gap_discover (gap_discover_observation);
        res = wait_for_callback (timeout);
        if (res != (int)BrainFlowExitCodes::STATUS_OK)
        {
            return res;
        }
        ble_cmd_gap_end_procedure ();
        return open_ble_dev ();
    }

    int open_device_mac_addr (void *param)
    {
        if (uart_open (uart_port))
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_READY_ERROR;
        }
        int res = reset_ble_dev ();
        if (res != (int)BrainFlowExitCodes::STATUS_OK)
        {
            return res;
        }
        exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
        state = State::OPEN_CALLED;
        char *mac_addr = (char *)param;
        // convert string mac addr to bd_addr struct
        for (unsigned int i = 0; i < strlen (mac_addr); i++)
        {
            mac_addr[i] = tolower (mac_addr[i]);
        }
        short unsigned int addr[6];
        if (sscanf (mac_addr, "%02hx:%02hx:%02hx:%02hx:%02hx:%02hx", &addr[5], &addr[4], &addr[3],
                &addr[2], &addr[1], &addr[0]) == 6)
        {
            for (int i = 0; i < 6; i++)
            {
                connect_addr.addr[i] = (uint8)addr[i];
            }
        }
        else
        {
            return (int)BrainFlowExitCodes::INVALID_ARGUMENTS_ERROR;
        }
        return open_ble_dev ();
    }

#ifdef __linux__
    int stop_stream (void *param)
    {
        // dirty hack to solve https://github.com/brainflow-dev/brainflow/issues/24
        if (!initialized)
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_CREATED_ERROR;
        }
        if (!should_stop_stream)
        {
            should_stop_stream = true;
            read_characteristic_thread.join ();
        }
        exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
        state = State::CONFIG_CALLED;
        if (characteristics.find ("CONTROL") == characteristics.end ())
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_CREATED_ERROR;
        }
        volatile bool stop_config_thread = false;
        std::thread config_thread = std::thread ([&] () {
            const char *stop_cmd = "h";
            int len = strlen (stop_cmd);
            while (!stop_config_thread)
            {
                ble_cmd_attclient_attribute_write (
                    connection, characteristics.find ("CONTROL"), len, (uint8 *)stop_cmd);
                ble_cmd_attclient_execute_write (connection, 1);
            }
        });
        int res = wait_for_callback (timeout);
        stop_config_thread = true;
        config_thread.join ();
        // need to remove generated by thread above messages from serial port buffer
        int l = 1;
        unsigned char temp_data;
        while (l > 0)
        {
            l = uart_rx (l, &temp_data, 1000);
        }
        return res;
    }
#else
    int stop_stream (void *param)
    {
        // hack above doesnt work well on windows and not needed for windows/macos
        if (!should_stop_stream)
        {
            should_stop_stream = true;
            read_characteristic_thread.join ();
        }
        const char *stop_cmd = "h";
        int res = config_device ((void *)stop_cmd);
        return res;
    }
#endif

    int start_stream (void *param)
    {
        // from silicanlabs forum - write 0x00001 to enable notifications
        uint8 configuration[] = {0x01, 0x00};
        for (uint16 ccid : ccids)
        {
            state = State::WRITE_TO_CLIENT_CHAR;
            exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
            ble_cmd_attclient_attribute_write (connection, ccid, 2, &configuration);
            ble_cmd_attclient_execute_write (connection, 1);
            int res = wait_for_callback (timeout);
            if (res != (int)BrainFlowExitCodes::STATUS_OK)
            {
                return res;
            }
        }
        int res = config_device ((void *)"v1");
        if (res != (int)BrainFlowExitCodes::STATUS_OK)
        {
            std::cout << "failed to write 1" << std::endl;
            return res;
        }
        res = config_device ((void *)"p63");
        if (res != (int)BrainFlowExitCodes::STATUS_OK)
        {
            std::cout << "failed to write 2" << std::endl;
            return res;
        }
        res = config_device ((void *)"d");
        if (res == (int)BrainFlowExitCodes::STATUS_OK)
        {
            should_stop_stream = false;
            read_characteristic_thread = std::thread (read_characteristic_worker);
        }

        return res;
    }

    int close_device (void *param)
    {
        if (!initialized)
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_CREATED_ERROR;
        }
        state = State::CLOSE_CALLED;

        if (!should_stop_stream)
        {
            stop_stream (NULL);
        }

        connection = -1;
        muse_handle_start = 0;
        muse_handle_end = 0;

        uart_close ();

        return (int)BrainFlowExitCodes::STATUS_OK;
    }

    int get_data (void *param)
    {
        if (!initialized)
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_CREATED_ERROR;
        }
        if (should_stop_stream)
        {
            return (int)BrainFlowExitCodes::EMPTY_BUFFER_ERROR;
        }
        state = State::GET_DATA_CALLED;
        int res = (int)BrainFlowExitCodes::STATUS_OK;
        // todo
        return res;
    }

    int release (void *param)
    {
        if (initialized)
        {
            close_device (NULL);
            state = State::NONE;
            initialized = false;
            exit_code = (int)BrainFlowExitCodes::SYNC_TIMEOUT_ERROR;
            ccids.clear ();
            characteristics.clear ();
        }

        return (int)BrainFlowExitCodes::STATUS_OK;
    }

    int config_device (void *param)
    {
        if (!initialized)
        {
            return (int)BrainFlowExitCodes::BOARD_NOT_CREATED_ERROR;
        }
        unsigned char *config = (unsigned char *)param;
        uint8 command[16];
        int len = (int)strlen ((char *)config);
        command[0] = (uint8)len + 1;
        for (int i = 0; i < len; i++)
        {
            command[i + 1] = int (config[i]);
        }
        command[len + 1] = 10;
        for (int i = 0; i < len + 2; i++)
        {
            std::cout << (int)command[i] << " ";
        }
        std::cout << std::endl;

        if (characteristics.find ("CONTROL") == characteristics.end ())
        {
            return (int)BrainFlowExitCodes::BOARD_WRITE_ERROR;
        }
        ble_cmd_attclient_write_command (connection, characteristics["CONTROL"], len + 2, command);
        return (int)BrainFlowExitCodes::STATUS_OK;
    }

} // MuseBLEDLib
