#pragma once


// info about services and chars
#define MUSE_ANTHENA_SERVICE_UUID 0xFE8D

#define MUSE_ANTHENA_GATT_ATTR_STREAM_TOGGLE "273e0001-4c4d-454d-96be-f03bac821358"
#define MUSE_ANTHENA_GATT_EEG "273e0013-4c4d-454d-96be-f03bac821358"
#define MUSE_ANTHENA_GATT_AUX "273e0014-4c4d-454d-96be-f03bac821358"

// info about packet type
#define MUSE_S_ANTHENA_EEG_FOUR_PACKET_TYPE 0x11
#define MUSE_S_ANTHENA_EEG_EIGHT_PACKET_TYPE 0x12
#define MUSE_S_ANTHENA_OPTICS_FOUR_PACKET_TYPE 0x34
#define MUSE_S_ANTHENA_OPTICS_EIGHT_PACKET_TYPE 0x35
#define MUSE_S_ANTHENA_OPTICS_SIXTEEN_PACKET_TYPE 0x36
#define MUSE_S_ANTHENA_SENSOR_PACKET_TYPE 0x47
#define MUSE_S_ANTHENA_STATUS_PACKET_TYPE 0x53
#define MUSE_S_ANTHENA_BATTERY_PACKET_TYPE 0x98

#define MUSE_S_ANTHENA_EEG_FOUR_PACKET_SIZE 32
#define MUSE_S_ANTHENA_EEG_EIGHT_PACKET_SIZE 32
#define MUSE_S_ANTHENA_OPTICS_FOUR_PACKET_SIZE 34
#define MUSE_S_ANTHENA_OPTICS_EIGHT_PACKET_SIZE 44
#define MUSE_S_ANTHENA_OPTICS_SIXTEEN_PACKET_SIZE 44
#define MUSE_S_ANTHENA_SENSOR_PACKET_SIZE 40
#define MUSE_S_ANTHENA_STATUS_PACKET_SIZE 28
