name: Conan Package

on: [push, pull_request]

jobs:
  ConanWindows:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [windows-2019]

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Get Conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.50.0 
    - name: Set Version
      id: version
      run: if ("tag" -eq $Env:GITHUB_REF_TYPE) { echo "::set-output name=version::$Env:GITHUB_REF_NAME" } else { echo "::set-output name=version::$Env:GITHUB_SHA" }
    - name: Check Version
      run: echo ${{ steps.version.outputs.version }}
    - name: Set Path
      run: |
        echo %GITHUB_WORKSPACE%\tools>>%GITHUB_PATH%
        echo %GITHUB_WORKSPACE%\installed64\lib>>%GITHUB_PATH%
        echo %GITHUB_WORKSPACE%\installed32\lib>>%GITHUB_PATH%
      shell: cmd
    - name: Run Conan packaging
      run: |
        conan create . demo/testing
      shell: cmd
      env:
        CONAN_CMAKE_SYSTEM_VERSION: 10.0.19041.0 