name: Run Valgrind

on: [push, pull_request]

jobs:
  RunValgrind:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-20.04]

    steps:
    # compile and prepare env
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Setup Cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Install Dependencies
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y libbluetooth-dev
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Compile BrainFlow
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        cmake -DBUILD_BLUETOOTH=ON -DBUILD_ONNX=ON -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Debug ..
        make
        make install
    - name: Build Get Data Test
      run: |
        cd $GITHUB_WORKSPACE/cpp_package/examples/get_data
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Debug ..
        make
    - name: Build Signal Processing Test
      run: |
        cd $GITHUB_WORKSPACE/cpp_package/examples/signal_processing
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Debug ..
        make
    - name: Build ML Demo Test
      run: |
        cd $GITHUB_WORKSPACE/cpp_package/examples/ml
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/installed -DCMAKE_BUILD_TYPE=Debug ..
        make
    - name: Install Valgrind
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y valgrind
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Install Python Dependencies
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install -y python3-setuptools python3-pygments
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Install Emulator
      run: |
        cd $GITHUB_WORKSPACE/emulator
        sudo -H python3 -m pip install -U .
    - name: Install Python test Dependencies
      run: sudo -H python3 -m pip install -r $GITHUB_WORKSPACE/python_package/examples/tests/requirements.txt
    - name: Setup Python Package
      run: |
        cd $GITHUB_WORKSPACE/python_package
        sudo -H python3 -m pip install -U .

    # start testing
    - name: Cyton Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/cyton_linux.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/brainflow_get_data --board-id 0 --serial-port
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Synthetic Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/brainflow_get_data --board-id -1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Twice
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/get_data_twice
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Galea Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/galea_udp.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/brainflow_get_data --board-id 3 --ip-address 127.0.0.1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Streaming Cpp
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/streaming_board_emulator.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/brainflow_get_data --board-id -2 --ip-address 225.1.1.1 --ip-port 6677 --master-board -1
    - name: Streaming Cpp Two Presets
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/streaming_board_emulator.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/brainflow_get_data --board-id -2 --ip-address 225.1.1.1 --ip-port 6677 --master-board -1 --ip-address-aux 225.1.1.1 --ip-port-aux 6678
    - name: Cyton Cpp Markers
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/cyton_linux.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/markers --board-id 0 --serial-port
    - name: Synthetic Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/markers --board-id -1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Galea Cpp Markers
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/galea_udp.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/markers --board-id 3 --ip-address 127.0.0.1
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Streaming Cpp Markers
      run: sudo -H python3 $GITHUB_WORKSPACE/emulator/brainflow_emulator/streaming_board_emulator.py valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/get_data/build/markers --board-id -2 --ip-address 225.1.1.1 --ip-port 6677 --master-board -1
    - name: Denoising Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/denoising
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Downsampling Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/downsampling
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Peaks Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/peaks_detection
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: CSP Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/csp
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Windowing Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/windowing
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Filters Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/signal_filtering
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Serialization Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/serialization
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: Transforms Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/transforms
      env:
          LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: BandPower Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/band_power
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
    - name: ICA Cpp
      run: valgrind --error-exitcode=1 --track-origins=yes --leak-check=full $GITHUB_WORKSPACE/cpp_package/examples/signal_processing/build/ica
      env:
        LD_LIBRARY_PATH: $GITHUB_WORKSPACE/installed/lib
